### ISSUE TITLE
Buildout job

### ISSUE THREAD

**Issue by okdv** [okdv/wrench-turn#3]
Backend
- [x] Create job endpoint
- [x] Edit job endpoint 
- [x] Delete job endpoint
- [x] Get job endpoint
- [x] List jobs endpoint (user, label, vehicle, status filters) #5 #2 #7 
- [x] Create job table
- [ ] Create job vehicle relationship table #5 
- [ ] Create job user relationship table #2 
- [x] Create job label relationship table #7 

Frontend
- [x] Create job page
- [x] Job page with edit/delete functionality
- [x] Search jobs page  (user, label, vehicle, status filters)
