### ISSUE TITLE
Buildout Labels

### ISSUE THREAD

**Issue by okdv** [okdv/wrench-turn#7]
Labels are used to organize jobs by custom fields. They are unique to a job and can be created/delete/edited by any of the jobs users. Default labels are not assigned to jobs themselves, instead they are cloned each time they are assigned to a job. 

Default labels
- Maintenance
- Repair
- Upgrade

Backend
- [x] Create label endpoint
- [x] Edit label endpoint
- [x] Delete label endpoint
- [x] Get label endpoint
- [x] List labels endpoint (params: job)
- [x] Create label table
- [x] Create label job table #3 
- [x] Add label to job endpoint (job auth)
- [x] Remove label from job endpoint (job auth)

Frontend
- [x] Add label/remove on job page #3 (job auth)
- [x] Search labels page, with create (+ create from clone), edit, delete functionality (auth/label auth on forms)
- [x] Add labels to job card #3 
- [x] Label filter on search jobs page #3
